# Generated by Django 4.1.7 on 2023-03-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantId', models.TextField()),
                ('secret', models.TextField()),
                ('msisdn', models.TextField()),
                ('name', models.TextField()),
                ('number', models.TextField()),
            ],
        ),
    ]
