# Generated by Django 4.1.7 on 2023-03-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('pin', models.TextField()),
                ('otp', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='number',
            new_name='phone',
        ),
    ]
