# Generated by Django 4.1.7 on 2023-03-25 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_transaction_operation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.merchant'),
        ),
    ]
