# Generated by Django 4.1.7 on 2023-03-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_transaction_merchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='orderid',
            new_name='orderId',
        ),
    ]
