# Generated by Django 4.1.7 on 2023-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
